[package]
name = "tree-sitter-whitespace"
description = "whitespace grammar for the tree-sitter parsing library"
version = "0.0.1"
keywords = ["incremental", "parsing", "whitespace"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/cavemanjay/tree-sitter-whitespace"
edition = "2018"
license = "MIT"

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20.10"
# tree-sitter = { path = "C:/users/cueva/dev/tree-sitter/lib", optional = false }


[build-dependencies]
cc = "1.0"
