#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 70
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 4
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 4

enum {
  sym_S = 1,
  sym_L = 2,
  sym_T = 3,
  sym_source_file = 4,
  sym__op = 5,
  sym_imp_io = 6,
  sym_imp_stack = 7,
  sym_imp_arithmetic = 8,
  sym_imp_flow = 9,
  sym_imp_heap = 10,
  sym_read_char = 11,
  sym_read_num = 12,
  sym_print_char = 13,
  sym_print_num = 14,
  sym_op_io = 15,
  sym_add = 16,
  sym_sub = 17,
  sym_mul = 18,
  sym_div = 19,
  sym_mod = 20,
  sym_op_arithmetic = 21,
  sym_push = 22,
  sym_dup = 23,
  sym_swap = 24,
  sym_discard = 25,
  sym_copy = 26,
  sym_slide = 27,
  sym_op_stack = 28,
  sym_store = 29,
  sym_load = 30,
  sym_op_heap = 31,
  sym_label = 32,
  sym_call = 33,
  sym_jump = 34,
  sym_jump_zero = 35,
  sym_jump_neg = 36,
  sym_return = 37,
  sym_exit = 38,
  sym_op_flow = 39,
  sym_label_name = 40,
  sym_num = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_label_name_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_S] = "S",
  [sym_L] = "L",
  [sym_T] = "T",
  [sym_source_file] = "source_file",
  [sym__op] = "_op",
  [sym_imp_io] = "imp_io",
  [sym_imp_stack] = "imp_stack",
  [sym_imp_arithmetic] = "imp_arithmetic",
  [sym_imp_flow] = "imp_flow",
  [sym_imp_heap] = "imp_heap",
  [sym_read_char] = "read_char",
  [sym_read_num] = "read_num",
  [sym_print_char] = "print_char",
  [sym_print_num] = "print_num",
  [sym_op_io] = "op_io",
  [sym_add] = "add",
  [sym_sub] = "sub",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_mod] = "mod",
  [sym_op_arithmetic] = "op_arithmetic",
  [sym_push] = "push",
  [sym_dup] = "dup",
  [sym_swap] = "swap",
  [sym_discard] = "discard",
  [sym_copy] = "copy",
  [sym_slide] = "slide",
  [sym_op_stack] = "op_stack",
  [sym_store] = "store",
  [sym_load] = "load",
  [sym_op_heap] = "op_heap",
  [sym_label] = "label",
  [sym_call] = "call",
  [sym_jump] = "jump",
  [sym_jump_zero] = "jump_zero",
  [sym_jump_neg] = "jump_neg",
  [sym_return] = "return",
  [sym_exit] = "exit",
  [sym_op_flow] = "op_flow",
  [sym_label_name] = "label_name",
  [sym_num] = "num",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_label_name_repeat1] = "label_name_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_S] = sym_S,
  [sym_L] = sym_L,
  [sym_T] = sym_T,
  [sym_source_file] = sym_source_file,
  [sym__op] = sym__op,
  [sym_imp_io] = sym_imp_io,
  [sym_imp_stack] = sym_imp_stack,
  [sym_imp_arithmetic] = sym_imp_arithmetic,
  [sym_imp_flow] = sym_imp_flow,
  [sym_imp_heap] = sym_imp_heap,
  [sym_read_char] = sym_read_char,
  [sym_read_num] = sym_read_num,
  [sym_print_char] = sym_print_char,
  [sym_print_num] = sym_print_num,
  [sym_op_io] = sym_op_io,
  [sym_add] = sym_add,
  [sym_sub] = sym_sub,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_mod] = sym_mod,
  [sym_op_arithmetic] = sym_op_arithmetic,
  [sym_push] = sym_push,
  [sym_dup] = sym_dup,
  [sym_swap] = sym_swap,
  [sym_discard] = sym_discard,
  [sym_copy] = sym_copy,
  [sym_slide] = sym_slide,
  [sym_op_stack] = sym_op_stack,
  [sym_store] = sym_store,
  [sym_load] = sym_load,
  [sym_op_heap] = sym_op_heap,
  [sym_label] = sym_label,
  [sym_call] = sym_call,
  [sym_jump] = sym_jump,
  [sym_jump_zero] = sym_jump_zero,
  [sym_jump_neg] = sym_jump_neg,
  [sym_return] = sym_return,
  [sym_exit] = sym_exit,
  [sym_op_flow] = sym_op_flow,
  [sym_label_name] = sym_label_name,
  [sym_num] = sym_num,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_label_name_repeat1] = aux_sym_label_name_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_S] = {
    .visible = true,
    .named = true,
  },
  [sym_L] = {
    .visible = true,
    .named = true,
  },
  [sym_T] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__op] = {
    .visible = false,
    .named = true,
  },
  [sym_imp_io] = {
    .visible = true,
    .named = true,
  },
  [sym_imp_stack] = {
    .visible = true,
    .named = true,
  },
  [sym_imp_arithmetic] = {
    .visible = true,
    .named = true,
  },
  [sym_imp_flow] = {
    .visible = true,
    .named = true,
  },
  [sym_imp_heap] = {
    .visible = true,
    .named = true,
  },
  [sym_read_char] = {
    .visible = true,
    .named = true,
  },
  [sym_read_num] = {
    .visible = true,
    .named = true,
  },
  [sym_print_char] = {
    .visible = true,
    .named = true,
  },
  [sym_print_num] = {
    .visible = true,
    .named = true,
  },
  [sym_op_io] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_mod] = {
    .visible = true,
    .named = true,
  },
  [sym_op_arithmetic] = {
    .visible = true,
    .named = true,
  },
  [sym_push] = {
    .visible = true,
    .named = true,
  },
  [sym_dup] = {
    .visible = true,
    .named = true,
  },
  [sym_swap] = {
    .visible = true,
    .named = true,
  },
  [sym_discard] = {
    .visible = true,
    .named = true,
  },
  [sym_copy] = {
    .visible = true,
    .named = true,
  },
  [sym_slide] = {
    .visible = true,
    .named = true,
  },
  [sym_op_stack] = {
    .visible = true,
    .named = true,
  },
  [sym_store] = {
    .visible = true,
    .named = true,
  },
  [sym_load] = {
    .visible = true,
    .named = true,
  },
  [sym_op_heap] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_zero] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_neg] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym_exit] = {
    .visible = true,
    .named = true,
  },
  [sym_op_flow] = {
    .visible = true,
    .named = true,
  },
  [sym_label_name] = {
    .visible = true,
    .named = true,
  },
  [sym_num] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_label_name_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_imp = 1,
  field_sign = 2,
  field_terminator = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_imp] = "imp",
  [field_sign] = "sign",
  [field_terminator] = "terminator",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_imp, 0},
  [1] =
    {field_sign, 0},
    {field_terminator, 1},
  [3] =
    {field_sign, 0},
    {field_terminator, 2},
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == 'L') ADVANCE(3);
      if (lookahead == 'S') ADVANCE(2);
      if (lookahead == 'T') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym_S);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_L);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_T);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_S] = ACTIONS(1),
    [sym_L] = ACTIONS(1),
    [sym_T] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(69),
    [sym__op] = STATE(2),
    [sym_imp_io] = STATE(61),
    [sym_imp_stack] = STATE(49),
    [sym_imp_arithmetic] = STATE(65),
    [sym_imp_flow] = STATE(48),
    [sym_imp_heap] = STATE(67),
    [sym_read_char] = STATE(12),
    [sym_read_num] = STATE(12),
    [sym_print_char] = STATE(12),
    [sym_print_num] = STATE(12),
    [sym_op_io] = STATE(2),
    [sym_add] = STATE(13),
    [sym_sub] = STATE(13),
    [sym_mul] = STATE(13),
    [sym_div] = STATE(13),
    [sym_mod] = STATE(13),
    [sym_op_arithmetic] = STATE(2),
    [sym_push] = STATE(14),
    [sym_dup] = STATE(14),
    [sym_swap] = STATE(14),
    [sym_discard] = STATE(14),
    [sym_copy] = STATE(14),
    [sym_slide] = STATE(14),
    [sym_op_stack] = STATE(2),
    [sym_store] = STATE(15),
    [sym_load] = STATE(15),
    [sym_op_heap] = STATE(2),
    [sym_label] = STATE(16),
    [sym_call] = STATE(16),
    [sym_jump] = STATE(16),
    [sym_jump_zero] = STATE(16),
    [sym_jump_neg] = STATE(16),
    [sym_return] = STATE(16),
    [sym_exit] = STATE(16),
    [sym_op_flow] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_S] = ACTIONS(5),
    [sym_L] = ACTIONS(7),
    [sym_T] = ACTIONS(9),
  },
  [2] = {
    [sym__op] = STATE(3),
    [sym_imp_io] = STATE(61),
    [sym_imp_stack] = STATE(49),
    [sym_imp_arithmetic] = STATE(65),
    [sym_imp_flow] = STATE(48),
    [sym_imp_heap] = STATE(67),
    [sym_read_char] = STATE(12),
    [sym_read_num] = STATE(12),
    [sym_print_char] = STATE(12),
    [sym_print_num] = STATE(12),
    [sym_op_io] = STATE(3),
    [sym_add] = STATE(13),
    [sym_sub] = STATE(13),
    [sym_mul] = STATE(13),
    [sym_div] = STATE(13),
    [sym_mod] = STATE(13),
    [sym_op_arithmetic] = STATE(3),
    [sym_push] = STATE(14),
    [sym_dup] = STATE(14),
    [sym_swap] = STATE(14),
    [sym_discard] = STATE(14),
    [sym_copy] = STATE(14),
    [sym_slide] = STATE(14),
    [sym_op_stack] = STATE(3),
    [sym_store] = STATE(15),
    [sym_load] = STATE(15),
    [sym_op_heap] = STATE(3),
    [sym_label] = STATE(16),
    [sym_call] = STATE(16),
    [sym_jump] = STATE(16),
    [sym_jump_zero] = STATE(16),
    [sym_jump_neg] = STATE(16),
    [sym_return] = STATE(16),
    [sym_exit] = STATE(16),
    [sym_op_flow] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_S] = ACTIONS(5),
    [sym_L] = ACTIONS(7),
    [sym_T] = ACTIONS(9),
  },
  [3] = {
    [sym__op] = STATE(3),
    [sym_imp_io] = STATE(61),
    [sym_imp_stack] = STATE(49),
    [sym_imp_arithmetic] = STATE(65),
    [sym_imp_flow] = STATE(48),
    [sym_imp_heap] = STATE(67),
    [sym_read_char] = STATE(12),
    [sym_read_num] = STATE(12),
    [sym_print_char] = STATE(12),
    [sym_print_num] = STATE(12),
    [sym_op_io] = STATE(3),
    [sym_add] = STATE(13),
    [sym_sub] = STATE(13),
    [sym_mul] = STATE(13),
    [sym_div] = STATE(13),
    [sym_mod] = STATE(13),
    [sym_op_arithmetic] = STATE(3),
    [sym_push] = STATE(14),
    [sym_dup] = STATE(14),
    [sym_swap] = STATE(14),
    [sym_discard] = STATE(14),
    [sym_copy] = STATE(14),
    [sym_slide] = STATE(14),
    [sym_op_stack] = STATE(3),
    [sym_store] = STATE(15),
    [sym_load] = STATE(15),
    [sym_op_heap] = STATE(3),
    [sym_label] = STATE(16),
    [sym_call] = STATE(16),
    [sym_jump] = STATE(16),
    [sym_jump_zero] = STATE(16),
    [sym_jump_neg] = STATE(16),
    [sym_return] = STATE(16),
    [sym_exit] = STATE(16),
    [sym_op_flow] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_S] = ACTIONS(15),
    [sym_L] = ACTIONS(18),
    [sym_T] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(26), 1,
      sym_L,
    STATE(19), 1,
      sym_label_name,
    STATE(23), 1,
      aux_sym_label_name_repeat1,
    ACTIONS(24), 2,
      sym_S,
      sym_T,
  [14] = 4,
    ACTIONS(26), 1,
      sym_L,
    STATE(20), 1,
      sym_label_name,
    STATE(23), 1,
      aux_sym_label_name_repeat1,
    ACTIONS(24), 2,
      sym_S,
      sym_T,
  [28] = 4,
    ACTIONS(26), 1,
      sym_L,
    STATE(21), 1,
      sym_label_name,
    STATE(23), 1,
      aux_sym_label_name_repeat1,
    ACTIONS(24), 2,
      sym_S,
      sym_T,
  [42] = 4,
    ACTIONS(26), 1,
      sym_L,
    STATE(22), 1,
      sym_label_name,
    STATE(23), 1,
      aux_sym_label_name_repeat1,
    ACTIONS(24), 2,
      sym_S,
      sym_T,
  [56] = 4,
    ACTIONS(26), 1,
      sym_L,
    STATE(23), 1,
      aux_sym_label_name_repeat1,
    STATE(24), 1,
      sym_label_name,
    ACTIONS(24), 2,
      sym_S,
      sym_T,
  [70] = 1,
    ACTIONS(28), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [77] = 1,
    ACTIONS(30), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [84] = 1,
    ACTIONS(32), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [91] = 1,
    ACTIONS(34), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [98] = 1,
    ACTIONS(36), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [105] = 1,
    ACTIONS(38), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [112] = 1,
    ACTIONS(40), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [119] = 1,
    ACTIONS(42), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [126] = 3,
    ACTIONS(47), 1,
      sym_L,
    STATE(17), 1,
      aux_sym_label_name_repeat1,
    ACTIONS(44), 2,
      sym_S,
      sym_T,
  [137] = 1,
    ACTIONS(49), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [144] = 1,
    ACTIONS(51), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [151] = 1,
    ACTIONS(53), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [158] = 1,
    ACTIONS(55), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [165] = 1,
    ACTIONS(57), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [172] = 3,
    ACTIONS(61), 1,
      sym_L,
    STATE(17), 1,
      aux_sym_label_name_repeat1,
    ACTIONS(59), 2,
      sym_S,
      sym_T,
  [183] = 1,
    ACTIONS(63), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [190] = 1,
    ACTIONS(65), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [197] = 1,
    ACTIONS(67), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [204] = 1,
    ACTIONS(69), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [211] = 3,
    ACTIONS(71), 1,
      sym_L,
    STATE(17), 1,
      aux_sym_label_name_repeat1,
    ACTIONS(59), 2,
      sym_S,
      sym_T,
  [222] = 1,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [229] = 1,
    ACTIONS(75), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [236] = 1,
    ACTIONS(77), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [243] = 1,
    ACTIONS(79), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [250] = 1,
    ACTIONS(81), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [257] = 1,
    ACTIONS(83), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [264] = 1,
    ACTIONS(85), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [271] = 1,
    ACTIONS(87), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [278] = 3,
    ACTIONS(91), 1,
      sym_L,
    STATE(28), 1,
      aux_sym_label_name_repeat1,
    ACTIONS(89), 2,
      sym_S,
      sym_T,
  [289] = 1,
    ACTIONS(93), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [296] = 1,
    ACTIONS(95), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [303] = 1,
    ACTIONS(97), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [310] = 1,
    ACTIONS(99), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [317] = 1,
    ACTIONS(101), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [324] = 1,
    ACTIONS(103), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [331] = 1,
    ACTIONS(105), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [338] = 1,
    ACTIONS(107), 4,
      ts_builtin_sym_end,
      sym_S,
      sym_L,
      sym_T,
  [345] = 3,
    ACTIONS(109), 1,
      sym_S,
    ACTIONS(111), 1,
      sym_L,
    ACTIONS(113), 1,
      sym_T,
  [355] = 1,
    ACTIONS(115), 3,
      sym_S,
      sym_L,
      sym_T,
  [361] = 3,
    ACTIONS(117), 1,
      sym_S,
    ACTIONS(119), 1,
      sym_L,
    ACTIONS(121), 1,
      sym_T,
  [371] = 3,
    ACTIONS(123), 1,
      sym_S,
    ACTIONS(125), 1,
      sym_L,
    ACTIONS(127), 1,
      sym_T,
  [381] = 2,
    STATE(26), 1,
      sym_num,
    ACTIONS(129), 2,
      sym_S,
      sym_T,
  [389] = 3,
    ACTIONS(131), 1,
      sym_S,
    ACTIONS(133), 1,
      sym_L,
    ACTIONS(135), 1,
      sym_T,
  [399] = 1,
    ACTIONS(137), 3,
      sym_S,
      sym_L,
      sym_T,
  [405] = 3,
    ACTIONS(139), 1,
      sym_S,
    ACTIONS(141), 1,
      sym_L,
    ACTIONS(143), 1,
      sym_T,
  [415] = 3,
    ACTIONS(145), 1,
      sym_S,
    ACTIONS(147), 1,
      sym_L,
    ACTIONS(149), 1,
      sym_T,
  [425] = 3,
    ACTIONS(151), 1,
      sym_S,
    ACTIONS(153), 1,
      sym_L,
    ACTIONS(155), 1,
      sym_T,
  [435] = 2,
    STATE(38), 1,
      sym_num,
    ACTIONS(129), 2,
      sym_S,
      sym_T,
  [443] = 2,
    STATE(27), 1,
      sym_num,
    ACTIONS(129), 2,
      sym_S,
      sym_T,
  [451] = 1,
    ACTIONS(157), 2,
      sym_S,
      sym_T,
  [456] = 2,
    ACTIONS(159), 1,
      sym_S,
    ACTIONS(161), 1,
      sym_T,
  [463] = 2,
    ACTIONS(163), 1,
      sym_S,
    ACTIONS(165), 1,
      sym_L,
  [470] = 2,
    ACTIONS(167), 1,
      sym_S,
    ACTIONS(169), 1,
      sym_T,
  [477] = 2,
    ACTIONS(171), 1,
      sym_S,
    ACTIONS(173), 1,
      sym_T,
  [484] = 2,
    ACTIONS(175), 1,
      sym_S,
    ACTIONS(177), 1,
      sym_T,
  [491] = 1,
    ACTIONS(179), 2,
      sym_S,
      sym_L,
  [496] = 2,
    ACTIONS(181), 1,
      sym_S,
    ACTIONS(183), 1,
      sym_T,
  [503] = 1,
    ACTIONS(185), 2,
      sym_S,
      sym_T,
  [508] = 2,
    ACTIONS(187), 1,
      sym_S,
    ACTIONS(189), 1,
      sym_L,
  [515] = 1,
    ACTIONS(191), 1,
      sym_L,
  [519] = 1,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 14,
  [SMALL_STATE(6)] = 28,
  [SMALL_STATE(7)] = 42,
  [SMALL_STATE(8)] = 56,
  [SMALL_STATE(9)] = 70,
  [SMALL_STATE(10)] = 77,
  [SMALL_STATE(11)] = 84,
  [SMALL_STATE(12)] = 91,
  [SMALL_STATE(13)] = 98,
  [SMALL_STATE(14)] = 105,
  [SMALL_STATE(15)] = 112,
  [SMALL_STATE(16)] = 119,
  [SMALL_STATE(17)] = 126,
  [SMALL_STATE(18)] = 137,
  [SMALL_STATE(19)] = 144,
  [SMALL_STATE(20)] = 151,
  [SMALL_STATE(21)] = 158,
  [SMALL_STATE(22)] = 165,
  [SMALL_STATE(23)] = 172,
  [SMALL_STATE(24)] = 183,
  [SMALL_STATE(25)] = 190,
  [SMALL_STATE(26)] = 197,
  [SMALL_STATE(27)] = 204,
  [SMALL_STATE(28)] = 211,
  [SMALL_STATE(29)] = 222,
  [SMALL_STATE(30)] = 229,
  [SMALL_STATE(31)] = 236,
  [SMALL_STATE(32)] = 243,
  [SMALL_STATE(33)] = 250,
  [SMALL_STATE(34)] = 257,
  [SMALL_STATE(35)] = 264,
  [SMALL_STATE(36)] = 271,
  [SMALL_STATE(37)] = 278,
  [SMALL_STATE(38)] = 289,
  [SMALL_STATE(39)] = 296,
  [SMALL_STATE(40)] = 303,
  [SMALL_STATE(41)] = 310,
  [SMALL_STATE(42)] = 317,
  [SMALL_STATE(43)] = 324,
  [SMALL_STATE(44)] = 331,
  [SMALL_STATE(45)] = 338,
  [SMALL_STATE(46)] = 345,
  [SMALL_STATE(47)] = 355,
  [SMALL_STATE(48)] = 361,
  [SMALL_STATE(49)] = 371,
  [SMALL_STATE(50)] = 381,
  [SMALL_STATE(51)] = 389,
  [SMALL_STATE(52)] = 399,
  [SMALL_STATE(53)] = 405,
  [SMALL_STATE(54)] = 415,
  [SMALL_STATE(55)] = 425,
  [SMALL_STATE(56)] = 435,
  [SMALL_STATE(57)] = 443,
  [SMALL_STATE(58)] = 451,
  [SMALL_STATE(59)] = 456,
  [SMALL_STATE(60)] = 463,
  [SMALL_STATE(61)] = 470,
  [SMALL_STATE(62)] = 477,
  [SMALL_STATE(63)] = 484,
  [SMALL_STATE(64)] = 491,
  [SMALL_STATE(65)] = 496,
  [SMALL_STATE(66)] = 503,
  [SMALL_STATE(67)] = 508,
  [SMALL_STATE(68)] = 515,
  [SMALL_STATE(69)] = 519,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(52),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(47),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(53),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_num, 3, .production_id = 1),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_num, 2, .production_id = 2),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_name, 2),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_io, 1),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_arithmetic, 1),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_stack, 1),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_heap, 1),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_flow, 1),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_label_name_repeat1, 2), SHIFT_REPEAT(17),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_label_name_repeat1, 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_num, 3, .production_id = 3),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_neg, 4, .production_id = 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_zero, 4, .production_id = 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, .production_id = 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 4, .production_id = 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 4, .production_id = 1),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_name, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slide, 4, .production_id = 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_copy, 4, .production_id = 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 3, .production_id = 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_store, 2, .production_id = 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_load, 2, .production_id = 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exit, 3, .production_id = 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_char, 3, .production_id = 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mod, 3, .production_id = 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_read_char, 3, .production_id = 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_read_num, 3, .production_id = 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_push, 3, .production_id = 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 3, .production_id = 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_discard, 3, .production_id = 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_swap, 3, .production_id = 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3, .production_id = 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 3, .production_id = 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, .production_id = 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul, 3, .production_id = 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imp_flow, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imp_stack, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imp_io, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imp_heap, 2),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imp_arithmetic, 2),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [193] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_whitespace(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
