#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 4
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 6

enum {
  anon_sym_ = 1,
  anon_sym_LF = 2,
  anon_sym_TAB = 3,
  sym_source_file = 4,
  sym__op = 5,
  sym__S = 6,
  sym__L = 7,
  sym__T = 8,
  sym_S = 9,
  sym_L = 10,
  sym_T = 11,
  sym__imp_io = 12,
  sym__imp_stack = 13,
  sym__imp_arithmetic = 14,
  sym__imp_flow = 15,
  sym__imp_heap = 16,
  sym_read_char = 17,
  sym_read_num = 18,
  sym_print_char = 19,
  sym_print_num = 20,
  sym_op_io = 21,
  sym_add = 22,
  sym_sub = 23,
  sym_mul = 24,
  sym_div = 25,
  sym_mod = 26,
  sym_op_arithmetic = 27,
  sym_push = 28,
  sym_dup = 29,
  sym_swap = 30,
  sym_discard = 31,
  sym_copy = 32,
  sym_slide = 33,
  sym_op_stack = 34,
  sym_store = 35,
  sym_load = 36,
  sym_op_heap = 37,
  sym_label = 38,
  sym_call = 39,
  sym_jump = 40,
  sym_jump_zero = 41,
  sym_jump_neg = 42,
  sym_return = 43,
  sym_exit = 44,
  sym_op_flow = 45,
  sym_label_name = 46,
  sym_num = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_label_name_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_] = " ",
  [anon_sym_LF] = "\n",
  [anon_sym_TAB] = "\t",
  [sym_source_file] = "source_file",
  [sym__op] = "_op",
  [sym__S] = "_S",
  [sym__L] = "_L",
  [sym__T] = "_T",
  [sym_S] = "S",
  [sym_L] = "L",
  [sym_T] = "T",
  [sym__imp_io] = "_imp_io",
  [sym__imp_stack] = "_imp_stack",
  [sym__imp_arithmetic] = "_imp_arithmetic",
  [sym__imp_flow] = "_imp_flow",
  [sym__imp_heap] = "_imp_heap",
  [sym_read_char] = "read_char",
  [sym_read_num] = "read_num",
  [sym_print_char] = "print_char",
  [sym_print_num] = "print_num",
  [sym_op_io] = "op_io",
  [sym_add] = "add",
  [sym_sub] = "sub",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_mod] = "mod",
  [sym_op_arithmetic] = "op_arithmetic",
  [sym_push] = "push",
  [sym_dup] = "dup",
  [sym_swap] = "swap",
  [sym_discard] = "discard",
  [sym_copy] = "copy",
  [sym_slide] = "slide",
  [sym_op_stack] = "op_stack",
  [sym_store] = "store",
  [sym_load] = "load",
  [sym_op_heap] = "op_heap",
  [sym_label] = "label",
  [sym_call] = "call",
  [sym_jump] = "jump",
  [sym_jump_zero] = "jump_zero",
  [sym_jump_neg] = "jump_neg",
  [sym_return] = "return",
  [sym_exit] = "exit",
  [sym_op_flow] = "op_flow",
  [sym_label_name] = "label_name",
  [sym_num] = "num",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_label_name_repeat1] = "label_name_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_] = anon_sym_,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_TAB] = anon_sym_TAB,
  [sym_source_file] = sym_source_file,
  [sym__op] = sym__op,
  [sym__S] = sym__S,
  [sym__L] = sym__L,
  [sym__T] = sym__T,
  [sym_S] = sym_S,
  [sym_L] = sym_L,
  [sym_T] = sym_T,
  [sym__imp_io] = sym__imp_io,
  [sym__imp_stack] = sym__imp_stack,
  [sym__imp_arithmetic] = sym__imp_arithmetic,
  [sym__imp_flow] = sym__imp_flow,
  [sym__imp_heap] = sym__imp_heap,
  [sym_read_char] = sym_read_char,
  [sym_read_num] = sym_read_num,
  [sym_print_char] = sym_print_char,
  [sym_print_num] = sym_print_num,
  [sym_op_io] = sym_op_io,
  [sym_add] = sym_add,
  [sym_sub] = sym_sub,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_mod] = sym_mod,
  [sym_op_arithmetic] = sym_op_arithmetic,
  [sym_push] = sym_push,
  [sym_dup] = sym_dup,
  [sym_swap] = sym_swap,
  [sym_discard] = sym_discard,
  [sym_copy] = sym_copy,
  [sym_slide] = sym_slide,
  [sym_op_stack] = sym_op_stack,
  [sym_store] = sym_store,
  [sym_load] = sym_load,
  [sym_op_heap] = sym_op_heap,
  [sym_label] = sym_label,
  [sym_call] = sym_call,
  [sym_jump] = sym_jump,
  [sym_jump_zero] = sym_jump_zero,
  [sym_jump_neg] = sym_jump_neg,
  [sym_return] = sym_return,
  [sym_exit] = sym_exit,
  [sym_op_flow] = sym_op_flow,
  [sym_label_name] = sym_label_name,
  [sym_num] = sym_num,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_label_name_repeat1] = aux_sym_label_name_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__op] = {
    .visible = false,
    .named = true,
  },
  [sym__S] = {
    .visible = false,
    .named = true,
  },
  [sym__L] = {
    .visible = false,
    .named = true,
  },
  [sym__T] = {
    .visible = false,
    .named = true,
  },
  [sym_S] = {
    .visible = true,
    .named = true,
  },
  [sym_L] = {
    .visible = true,
    .named = true,
  },
  [sym_T] = {
    .visible = true,
    .named = true,
  },
  [sym__imp_io] = {
    .visible = false,
    .named = true,
  },
  [sym__imp_stack] = {
    .visible = false,
    .named = true,
  },
  [sym__imp_arithmetic] = {
    .visible = false,
    .named = true,
  },
  [sym__imp_flow] = {
    .visible = false,
    .named = true,
  },
  [sym__imp_heap] = {
    .visible = false,
    .named = true,
  },
  [sym_read_char] = {
    .visible = true,
    .named = true,
  },
  [sym_read_num] = {
    .visible = true,
    .named = true,
  },
  [sym_print_char] = {
    .visible = true,
    .named = true,
  },
  [sym_print_num] = {
    .visible = true,
    .named = true,
  },
  [sym_op_io] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_mod] = {
    .visible = true,
    .named = true,
  },
  [sym_op_arithmetic] = {
    .visible = true,
    .named = true,
  },
  [sym_push] = {
    .visible = true,
    .named = true,
  },
  [sym_dup] = {
    .visible = true,
    .named = true,
  },
  [sym_swap] = {
    .visible = true,
    .named = true,
  },
  [sym_discard] = {
    .visible = true,
    .named = true,
  },
  [sym_copy] = {
    .visible = true,
    .named = true,
  },
  [sym_slide] = {
    .visible = true,
    .named = true,
  },
  [sym_op_stack] = {
    .visible = true,
    .named = true,
  },
  [sym_store] = {
    .visible = true,
    .named = true,
  },
  [sym_load] = {
    .visible = true,
    .named = true,
  },
  [sym_op_heap] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_zero] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_neg] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym_exit] = {
    .visible = true,
    .named = true,
  },
  [sym_op_flow] = {
    .visible = true,
    .named = true,
  },
  [sym_label_name] = {
    .visible = true,
    .named = true,
  },
  [sym_num] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_label_name_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_label_name = 1,
  field_num = 2,
  field_sign = 3,
  field_terminator = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_label_name] = "label_name",
  [field_num] = "num",
  [field_sign] = "sign",
  [field_terminator] = "terminator",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_num, 2},
  [1] =
    {field_sign, 0},
    {field_terminator, 1},
  [3] =
    {field_num, 3},
  [4] =
    {field_label_name, 3},
  [5] =
    {field_sign, 0},
    {field_terminator, 2},
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '\t') ADVANCE(4);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_TAB);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_TAB] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(70),
    [sym__op] = STATE(3),
    [sym__S] = STATE(12),
    [sym__L] = STATE(14),
    [sym__T] = STATE(17),
    [sym__imp_io] = STATE(40),
    [sym__imp_stack] = STATE(12),
    [sym__imp_arithmetic] = STATE(63),
    [sym__imp_flow] = STATE(14),
    [sym__imp_heap] = STATE(57),
    [sym_read_char] = STATE(53),
    [sym_read_num] = STATE(53),
    [sym_print_char] = STATE(53),
    [sym_print_num] = STATE(53),
    [sym_op_io] = STATE(3),
    [sym_add] = STATE(51),
    [sym_sub] = STATE(51),
    [sym_mul] = STATE(51),
    [sym_div] = STATE(51),
    [sym_mod] = STATE(51),
    [sym_op_arithmetic] = STATE(3),
    [sym_push] = STATE(50),
    [sym_dup] = STATE(50),
    [sym_swap] = STATE(50),
    [sym_discard] = STATE(50),
    [sym_copy] = STATE(50),
    [sym_slide] = STATE(50),
    [sym_op_stack] = STATE(3),
    [sym_store] = STATE(49),
    [sym_load] = STATE(49),
    [sym_op_heap] = STATE(3),
    [sym_label] = STATE(48),
    [sym_call] = STATE(48),
    [sym_jump] = STATE(48),
    [sym_jump_zero] = STATE(48),
    [sym_jump_neg] = STATE(48),
    [sym_return] = STATE(48),
    [sym_exit] = STATE(48),
    [sym_op_flow] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(7),
    [anon_sym_TAB] = ACTIONS(9),
  },
  [2] = {
    [sym__op] = STATE(2),
    [sym__S] = STATE(12),
    [sym__L] = STATE(14),
    [sym__T] = STATE(17),
    [sym__imp_io] = STATE(40),
    [sym__imp_stack] = STATE(12),
    [sym__imp_arithmetic] = STATE(63),
    [sym__imp_flow] = STATE(14),
    [sym__imp_heap] = STATE(57),
    [sym_read_char] = STATE(53),
    [sym_read_num] = STATE(53),
    [sym_print_char] = STATE(53),
    [sym_print_num] = STATE(53),
    [sym_op_io] = STATE(2),
    [sym_add] = STATE(51),
    [sym_sub] = STATE(51),
    [sym_mul] = STATE(51),
    [sym_div] = STATE(51),
    [sym_mod] = STATE(51),
    [sym_op_arithmetic] = STATE(2),
    [sym_push] = STATE(50),
    [sym_dup] = STATE(50),
    [sym_swap] = STATE(50),
    [sym_discard] = STATE(50),
    [sym_copy] = STATE(50),
    [sym_slide] = STATE(50),
    [sym_op_stack] = STATE(2),
    [sym_store] = STATE(49),
    [sym_load] = STATE(49),
    [sym_op_heap] = STATE(2),
    [sym_label] = STATE(48),
    [sym_call] = STATE(48),
    [sym_jump] = STATE(48),
    [sym_jump_zero] = STATE(48),
    [sym_jump_neg] = STATE(48),
    [sym_return] = STATE(48),
    [sym_exit] = STATE(48),
    [sym_op_flow] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(16),
    [anon_sym_TAB] = ACTIONS(19),
  },
  [3] = {
    [sym__op] = STATE(2),
    [sym__S] = STATE(12),
    [sym__L] = STATE(14),
    [sym__T] = STATE(17),
    [sym__imp_io] = STATE(40),
    [sym__imp_stack] = STATE(12),
    [sym__imp_arithmetic] = STATE(63),
    [sym__imp_flow] = STATE(14),
    [sym__imp_heap] = STATE(57),
    [sym_read_char] = STATE(53),
    [sym_read_num] = STATE(53),
    [sym_print_char] = STATE(53),
    [sym_print_num] = STATE(53),
    [sym_op_io] = STATE(2),
    [sym_add] = STATE(51),
    [sym_sub] = STATE(51),
    [sym_mul] = STATE(51),
    [sym_div] = STATE(51),
    [sym_mod] = STATE(51),
    [sym_op_arithmetic] = STATE(2),
    [sym_push] = STATE(50),
    [sym_dup] = STATE(50),
    [sym_swap] = STATE(50),
    [sym_discard] = STATE(50),
    [sym_copy] = STATE(50),
    [sym_slide] = STATE(50),
    [sym_op_stack] = STATE(2),
    [sym_store] = STATE(49),
    [sym_load] = STATE(49),
    [sym_op_heap] = STATE(2),
    [sym_label] = STATE(48),
    [sym_call] = STATE(48),
    [sym_jump] = STATE(48),
    [sym_jump_zero] = STATE(48),
    [sym_jump_neg] = STATE(48),
    [sym_return] = STATE(48),
    [sym_exit] = STATE(48),
    [sym_op_flow] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(22),
    [anon_sym_] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(7),
    [anon_sym_TAB] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(24), 1,
      anon_sym_,
    ACTIONS(26), 1,
      anon_sym_LF,
    ACTIONS(28), 1,
      anon_sym_TAB,
    STATE(55), 1,
      sym_label_name,
    STATE(61), 1,
      sym_L,
    STATE(10), 3,
      sym_S,
      sym_T,
      aux_sym_label_name_repeat1,
  [21] = 6,
    ACTIONS(24), 1,
      anon_sym_,
    ACTIONS(26), 1,
      anon_sym_LF,
    ACTIONS(28), 1,
      anon_sym_TAB,
    STATE(61), 1,
      sym_L,
    STATE(62), 1,
      sym_label_name,
    STATE(10), 3,
      sym_S,
      sym_T,
      aux_sym_label_name_repeat1,
  [42] = 6,
    ACTIONS(24), 1,
      anon_sym_,
    ACTIONS(26), 1,
      anon_sym_LF,
    ACTIONS(28), 1,
      anon_sym_TAB,
    STATE(46), 1,
      sym_label_name,
    STATE(61), 1,
      sym_L,
    STATE(10), 3,
      sym_S,
      sym_T,
      aux_sym_label_name_repeat1,
  [63] = 6,
    ACTIONS(24), 1,
      anon_sym_,
    ACTIONS(26), 1,
      anon_sym_LF,
    ACTIONS(28), 1,
      anon_sym_TAB,
    STATE(47), 1,
      sym_label_name,
    STATE(61), 1,
      sym_L,
    STATE(10), 3,
      sym_S,
      sym_T,
      aux_sym_label_name_repeat1,
  [84] = 6,
    ACTIONS(24), 1,
      anon_sym_,
    ACTIONS(26), 1,
      anon_sym_LF,
    ACTIONS(28), 1,
      anon_sym_TAB,
    STATE(54), 1,
      sym_label_name,
    STATE(61), 1,
      sym_L,
    STATE(10), 3,
      sym_S,
      sym_T,
      aux_sym_label_name_repeat1,
  [105] = 5,
    ACTIONS(24), 1,
      anon_sym_,
    ACTIONS(28), 1,
      anon_sym_TAB,
    ACTIONS(30), 1,
      anon_sym_LF,
    STATE(56), 1,
      sym__L,
    STATE(11), 3,
      sym_S,
      sym_T,
      aux_sym_label_name_repeat1,
  [123] = 5,
    ACTIONS(24), 1,
      anon_sym_,
    ACTIONS(26), 1,
      anon_sym_LF,
    ACTIONS(28), 1,
      anon_sym_TAB,
    STATE(29), 1,
      sym_L,
    STATE(13), 3,
      sym_S,
      sym_T,
      aux_sym_label_name_repeat1,
  [141] = 5,
    ACTIONS(24), 1,
      anon_sym_,
    ACTIONS(28), 1,
      anon_sym_TAB,
    ACTIONS(32), 1,
      anon_sym_LF,
    STATE(41), 1,
      sym__L,
    STATE(13), 3,
      sym_S,
      sym_T,
      aux_sym_label_name_repeat1,
  [159] = 6,
    ACTIONS(34), 1,
      anon_sym_,
    ACTIONS(36), 1,
      anon_sym_LF,
    ACTIONS(38), 1,
      anon_sym_TAB,
    STATE(18), 1,
      sym__L,
    STATE(22), 1,
      sym__S,
    STATE(27), 1,
      sym__T,
  [178] = 4,
    ACTIONS(40), 1,
      anon_sym_,
    ACTIONS(43), 1,
      anon_sym_LF,
    ACTIONS(45), 1,
      anon_sym_TAB,
    STATE(13), 3,
      sym_S,
      sym_T,
      aux_sym_label_name_repeat1,
  [193] = 6,
    ACTIONS(48), 1,
      anon_sym_,
    ACTIONS(50), 1,
      anon_sym_LF,
    ACTIONS(52), 1,
      anon_sym_TAB,
    STATE(16), 1,
      sym__S,
    STATE(19), 1,
      sym__T,
    STATE(69), 1,
      sym__L,
  [212] = 6,
    ACTIONS(54), 1,
      anon_sym_,
    ACTIONS(56), 1,
      anon_sym_LF,
    ACTIONS(58), 1,
      anon_sym_TAB,
    STATE(42), 1,
      sym__S,
    STATE(43), 1,
      sym__L,
    STATE(44), 1,
      sym__T,
  [231] = 6,
    ACTIONS(60), 1,
      anon_sym_,
    ACTIONS(62), 1,
      anon_sym_LF,
    ACTIONS(64), 1,
      anon_sym_TAB,
    STATE(4), 1,
      sym__L,
    STATE(5), 1,
      sym__S,
    STATE(8), 1,
      sym__T,
  [250] = 6,
    ACTIONS(66), 1,
      anon_sym_,
    ACTIONS(68), 1,
      anon_sym_LF,
    ACTIONS(70), 1,
      anon_sym_TAB,
    STATE(66), 1,
      sym__S,
    STATE(67), 1,
      sym__T,
    STATE(68), 1,
      sym__L,
  [269] = 6,
    ACTIONS(72), 1,
      anon_sym_,
    ACTIONS(74), 1,
      anon_sym_LF,
    ACTIONS(76), 1,
      anon_sym_TAB,
    STATE(37), 1,
      sym__S,
    STATE(38), 1,
      sym__L,
    STATE(39), 1,
      sym__T,
  [288] = 6,
    ACTIONS(78), 1,
      anon_sym_,
    ACTIONS(80), 1,
      anon_sym_LF,
    ACTIONS(82), 1,
      anon_sym_TAB,
    STATE(6), 1,
      sym__T,
    STATE(7), 1,
      sym__S,
    STATE(52), 1,
      sym__L,
  [307] = 3,
    STATE(59), 1,
      sym_num,
    ACTIONS(84), 2,
      anon_sym_,
      anon_sym_TAB,
    STATE(9), 2,
      sym__S,
      sym__T,
  [319] = 3,
    STATE(58), 1,
      sym_num,
    ACTIONS(84), 2,
      anon_sym_,
      anon_sym_TAB,
    STATE(9), 2,
      sym__S,
      sym__T,
  [331] = 3,
    STATE(36), 1,
      sym_num,
    ACTIONS(84), 2,
      anon_sym_,
      anon_sym_TAB,
    STATE(9), 2,
      sym__S,
      sym__T,
  [343] = 1,
    ACTIONS(86), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [350] = 1,
    ACTIONS(88), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [357] = 4,
    ACTIONS(90), 1,
      anon_sym_,
    ACTIONS(92), 1,
      anon_sym_TAB,
    STATE(32), 1,
      sym__S,
    STATE(33), 1,
      sym__T,
  [370] = 4,
    ACTIONS(94), 1,
      anon_sym_,
    ACTIONS(96), 1,
      anon_sym_TAB,
    STATE(34), 1,
      sym__S,
    STATE(35), 1,
      sym__T,
  [383] = 4,
    ACTIONS(98), 1,
      anon_sym_,
    ACTIONS(100), 1,
      anon_sym_LF,
    STATE(20), 1,
      sym__L,
    STATE(21), 1,
      sym__S,
  [396] = 4,
    ACTIONS(102), 1,
      anon_sym_,
    ACTIONS(104), 1,
      anon_sym_TAB,
    STATE(24), 1,
      sym__T,
    STATE(45), 1,
      sym__S,
  [409] = 1,
    ACTIONS(106), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [416] = 1,
    ACTIONS(108), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [423] = 1,
    ACTIONS(110), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [430] = 1,
    ACTIONS(112), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [437] = 1,
    ACTIONS(114), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [444] = 1,
    ACTIONS(116), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [451] = 1,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [458] = 1,
    ACTIONS(120), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [465] = 1,
    ACTIONS(122), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [472] = 1,
    ACTIONS(124), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [479] = 1,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [486] = 4,
    ACTIONS(128), 1,
      anon_sym_,
    ACTIONS(130), 1,
      anon_sym_TAB,
    STATE(25), 1,
      sym__S,
    STATE(26), 1,
      sym__T,
  [499] = 1,
    ACTIONS(132), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [506] = 1,
    ACTIONS(134), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [513] = 1,
    ACTIONS(136), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [520] = 1,
    ACTIONS(138), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [527] = 1,
    ACTIONS(140), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [534] = 1,
    ACTIONS(142), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [541] = 1,
    ACTIONS(144), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [548] = 1,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [555] = 1,
    ACTIONS(148), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [562] = 1,
    ACTIONS(150), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [569] = 1,
    ACTIONS(152), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [576] = 1,
    ACTIONS(154), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [583] = 1,
    ACTIONS(156), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [590] = 1,
    ACTIONS(158), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [597] = 1,
    ACTIONS(160), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [604] = 1,
    ACTIONS(162), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [611] = 4,
    ACTIONS(164), 1,
      anon_sym_,
    ACTIONS(166), 1,
      anon_sym_TAB,
    STATE(30), 1,
      sym__S,
    STATE(31), 1,
      sym__T,
  [624] = 1,
    ACTIONS(168), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [631] = 1,
    ACTIONS(170), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [638] = 1,
    ACTIONS(172), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [645] = 1,
    ACTIONS(174), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [652] = 1,
    ACTIONS(176), 4,
      ts_builtin_sym_end,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [659] = 4,
    ACTIONS(178), 1,
      anon_sym_,
    ACTIONS(180), 1,
      anon_sym_TAB,
    STATE(15), 1,
      sym__S,
    STATE(28), 1,
      sym__T,
  [672] = 1,
    ACTIONS(182), 3,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [678] = 1,
    ACTIONS(184), 3,
      anon_sym_,
      anon_sym_LF,
      anon_sym_TAB,
  [684] = 1,
    ACTIONS(186), 2,
      anon_sym_,
      anon_sym_TAB,
  [689] = 1,
    ACTIONS(188), 2,
      anon_sym_,
      anon_sym_TAB,
  [694] = 1,
    ACTIONS(190), 2,
      anon_sym_,
      anon_sym_TAB,
  [699] = 2,
    ACTIONS(192), 1,
      anon_sym_LF,
    STATE(23), 1,
      sym__L,
  [706] = 1,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 21,
  [SMALL_STATE(6)] = 42,
  [SMALL_STATE(7)] = 63,
  [SMALL_STATE(8)] = 84,
  [SMALL_STATE(9)] = 105,
  [SMALL_STATE(10)] = 123,
  [SMALL_STATE(11)] = 141,
  [SMALL_STATE(12)] = 159,
  [SMALL_STATE(13)] = 178,
  [SMALL_STATE(14)] = 193,
  [SMALL_STATE(15)] = 212,
  [SMALL_STATE(16)] = 231,
  [SMALL_STATE(17)] = 250,
  [SMALL_STATE(18)] = 269,
  [SMALL_STATE(19)] = 288,
  [SMALL_STATE(20)] = 307,
  [SMALL_STATE(21)] = 319,
  [SMALL_STATE(22)] = 331,
  [SMALL_STATE(23)] = 343,
  [SMALL_STATE(24)] = 350,
  [SMALL_STATE(25)] = 357,
  [SMALL_STATE(26)] = 370,
  [SMALL_STATE(27)] = 383,
  [SMALL_STATE(28)] = 396,
  [SMALL_STATE(29)] = 409,
  [SMALL_STATE(30)] = 416,
  [SMALL_STATE(31)] = 423,
  [SMALL_STATE(32)] = 430,
  [SMALL_STATE(33)] = 437,
  [SMALL_STATE(34)] = 444,
  [SMALL_STATE(35)] = 451,
  [SMALL_STATE(36)] = 458,
  [SMALL_STATE(37)] = 465,
  [SMALL_STATE(38)] = 472,
  [SMALL_STATE(39)] = 479,
  [SMALL_STATE(40)] = 486,
  [SMALL_STATE(41)] = 499,
  [SMALL_STATE(42)] = 506,
  [SMALL_STATE(43)] = 513,
  [SMALL_STATE(44)] = 520,
  [SMALL_STATE(45)] = 527,
  [SMALL_STATE(46)] = 534,
  [SMALL_STATE(47)] = 541,
  [SMALL_STATE(48)] = 548,
  [SMALL_STATE(49)] = 555,
  [SMALL_STATE(50)] = 562,
  [SMALL_STATE(51)] = 569,
  [SMALL_STATE(52)] = 576,
  [SMALL_STATE(53)] = 583,
  [SMALL_STATE(54)] = 590,
  [SMALL_STATE(55)] = 597,
  [SMALL_STATE(56)] = 604,
  [SMALL_STATE(57)] = 611,
  [SMALL_STATE(58)] = 624,
  [SMALL_STATE(59)] = 631,
  [SMALL_STATE(60)] = 638,
  [SMALL_STATE(61)] = 645,
  [SMALL_STATE(62)] = 652,
  [SMALL_STATE(63)] = 659,
  [SMALL_STATE(64)] = 672,
  [SMALL_STATE(65)] = 678,
  [SMALL_STATE(66)] = 684,
  [SMALL_STATE(67)] = 689,
  [SMALL_STATE(68)] = 694,
  [SMALL_STATE(69)] = 699,
  [SMALL_STATE(70)] = 706,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(12),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(14),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(17),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_label_name_repeat1, 2), SHIFT_REPEAT(65),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_label_name_repeat1, 2),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_label_name_repeat1, 2), SHIFT_REPEAT(64),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exit, 3),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mod, 3),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_name, 2),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_store, 2),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_load, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_char, 3),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_num, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_read_char, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_read_num, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_push, 3, .production_id = 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_discard, 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_swap, 3),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_num, 3, .production_id = 5),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul, 3),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_neg, 4, .production_id = 4),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_zero, 4, .production_id = 4),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_flow, 1),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_heap, 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_stack, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_arithmetic, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 3),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_io, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, .production_id = 4),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 4, .production_id = 4),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_num, 2, .production_id = 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_copy, 4, .production_id = 3),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slide, 4, .production_id = 3),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_L, 1),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_name, 1),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 4, .production_id = 4),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_T, 1),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_S, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__imp_arithmetic, 2),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__imp_heap, 2),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__imp_io, 2),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [194] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_whitespace(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
